$psise.CurrentPowerShellTab.Files.add("C:\Users\nepeters\Dropbox\Projects\TR21\Demos\4 - DSC Extension\1 - TR21 DSC Configuration\TR21DSC.ps1")
$psise.CurrentPowerShellTab.Files.add("C:\Users\nepeters\Dropbox\Projects\TR21\Demos\4 - DSC Extension\2 - Upload DSC Configuration to Azure\UploadDSCAzure.ps1")
$psise.CurrentPowerShellTab.Files.add("C:\Users\nepeters\Dropbox\Projects\TR21\Demos\4 - DSC Extension\3 - Apply DSC Configuration to Exsisting VM\Set-AzureVMDSCExtensionExsisting_Splat.ps1")
$psise.CurrentPowerShellTab.Files.add("C:\Users\nepeters\Dropbox\Projects\TR21\Demos\4 - DSC Extension\3 - Apply DSC Configuration to Exsisting VM\Set-AzureVMDSCExtensionExsisting.ps1")
$psise.CurrentPowerShellTab.Files.add("C:\Users\nepeters\Dropbox\Projects\TR21\Demos\4 - DSC Extension\4 - Apply DSC Configuration to New VM\Set-AzureVMDSCExtension_NewVM.ps1")
